var ETO_CONFIG_DEFAULT={title:"ETO",version:"0.0.1",DEBUG:!0,configuration_file:"config.json",basepath:"",datapath:"data/",menu_key:27,renderer_params:{precision:THREE.highp,alpha:!0,antialias:!0},camera_fov:75,camera_near:1,camera_far:1E3,camera_position:{x:20,y:40,z:20},camera_up:{x:0,y:1,z:0},camera_lookat:{x:0,y:20,z:0},sky_size:300,sky_color:7368848,play_music:!1,master_volume:1,audio_types:[{suffix:".mp3",type:"audio/mpeg"},{suffix:".ogg",type:"audio/ogg"}],gravity:{x:0,y:-1,z:0},forward:{x:0,
y:0,z:1},feet_start_height:100,feet_end_height:1,walk_speed:.2,walk_turn_speed:.03,fly_speed:.3,fly_turn_speed:.03,projectile_speed:.1,projectile_turn_speed:.3,explosion_size:1,item_cooldown:1,autoaim:2*Math.PI/360,player_start_health:50},Input={keys:[],TAB:9,SHIFT:16,CTRL:17,ALT:18,ESC:27,SPACE:32,LEFT:37,UP:38,RIGHT:39,DOWN:40,KEYA:65,KEYW:87,KEYD:68,KEYS:83,PIPE:0,keyUp:function(a){a.preventDefault();a.keyCode==game.config.menu_key&&game.toggleMenu();Input.keys[a.keyCode]=!1},keyDown:function(a){a.preventDefault();
Input.keys[a.keyCode]=!0}},Audio=function(){this.context=new AudioContext;this.masterGain=this.context.createGain();this.masterGain.connect(this.context.destination);this.setVolume(game.config.master_volume)};Audio.prototype.getDestination=function(){return this.masterGain};Audio.prototype.setVolume=function(a){this.masterGain.gain.value=a};var Sound=function(a){this.buffer=a};
Audio.prototype.decodeAudio=function(a,b){this.context.decodeAudioData(b,function(b){a.buffer=b;game.log("Sound decoded!",b)},function(){game.error("Can't decode "+url)})};Audio.prototype.createPanner=function(){context.createPanner().connect(this.masterGain)};Audio.prototype.updatePannerPosition=function(a,b){Entity.vector.setFromMatrixPosition(b.graphics.matrixWorld);a.setPosition(Entity.vector.x,Entity.vector.y,Entity.vector.z)};
Audio.prototype.updateListenerPosition=function(a){a.position.set(x,y,z);a.updateMatrixWorld();Entity.vector.setFromMatrixPosition(a.matrixWorld);this.context.listener.setPosition(Entity.vector.x,Entity.vector.y,Entity.vector.z)};
Audio.prototype.playSound=function(a,b,c,d){if("undefined"===typeof a||null===a)game.error("Audio: trying to play empty buffer");else{if("undefined"===typeof b||null===b)game.log("Audio: Empty source given, creating a new one"),b=this.context.createBufferSource();b.buffer=a;b.connect(this.getDestination());"undefined"!==typeof d&&null!==d?b.start(d):b.start(0)}};
var Entity=function(a){this.parent=a;a=new THREE.MeshBasicMaterial({color:11583696});var b=new THREE.BoxGeometry(.2,10,.2);this.feet=new THREE.Mesh(b,a);this.graphics=null};Entity.gravity=new THREE.Vector3(ETO_CONFIG_DEFAULT.gravity.x,ETO_CONFIG_DEFAULT.gravity.y,ETO_CONFIG_DEFAULT.gravity.z);Entity.up=new THREE.Vector3(-ETO_CONFIG_DEFAULT.gravity.x,-ETO_CONFIG_DEFAULT.gravity.y,-ETO_CONFIG_DEFAULT.gravity.z);
Entity.forward=new THREE.Vector3(ETO_CONFIG_DEFAULT.forward.x,ETO_CONFIG_DEFAULT.forward.y,ETO_CONFIG_DEFAULT.forward.z);Entity.matrix=new THREE.Matrix4;Entity.quaternion=new THREE.Quaternion;Entity.vector=new THREE.Vector3;Entity.vector2=new THREE.Vector3;Entity.vector3=new THREE.Vector3;Entity.ray=new THREE.Raycaster;Entity.hasComponent=function(a){return"undefined"!==typeof a&&null!==a};
Entity.prototype.startUpdate=function(a){Entity.hasComponent(this.graphics)&&Entity.hasComponent(this.physics)&&this.physics.oldPosition.copy(this.graphics.position);if(Entity.hasComponent(this.player))return 0>=this.ai.health&&this.playerDies(),this.ai.alive;if(Entity.hasComponent(this.item)&&Entity.hasComponent(this.ai.alive)||Entity.hasComponent(this.ai)&&Entity.hasComponent(this.ai.explosionstart)&&Entity.hasComponent(this.ai.alive))return this.ai.alive;game.log("startUpdate called for unknown entity",
this);return!1};Entity.prototype.setAvatar=function(a){this.avatar=a};
Entity.prototype.setProjectile=function(a){this.item=a;this.ai={type:"projectile",alive:!0,speed:this.item.speed*game.config.projectile_speed,turn:this.item.turn*game.config.projectile_turn_speed};this.physics={oldPosition:new THREE.Vector3,oldDelta:1,gravity:Entity.hasComponent(this.item.gravity)&&this.item.gravity};if(this.physics.gravity){a=Entity.gravity.length;var b=Math.pow(this.ai.speed,2),c=this.item.range;Math.abs(c*a)<=Math.abs(b)?this.physics.theta=Math.asin(c*a/b)/2:(game.log("Impossible ballistics given in ",
this.item),this.physics.theta=1)}};
Entity.prototype.setPlayer=function(a){this.player=a;Entity.hasComponent(this.player.kills)||(this.player.kills=0);Entity.hasComponent(this.player.deaths)||(this.player.deaths=0);this.ai={type:this.avatar.type,alive:!0,health:a.strength*game.config.player_start_health};"flyer"==this.ai.type?(this.ai.speed=this.avatar.speed*game.config.fly_speed,this.ai.turn=this.avatar.turn*game.config.fly_turn_speed):(this.ai.speed=this.avatar.speed*game.config.walk_speed,this.ai.turn=this.avatar.turn*game.config.walk_turn_speed);
this.physics={oldPosition:new THREE.Vector3}};Entity.prototype.setItem=function(a){this.ai={lastFired:-1E3};this.item=a;this.setModel(this.item.model);a=new THREE.BoxGeometry(.2,.2,10.2);var b=new THREE.MeshBasicMaterial({color:14684368});this.shot=new THREE.Mesh(a,b);a=new THREE.BoxGeometry(1,1,1);b=new THREE.MeshBasicMaterial({color:16715792});this.crosshair=new THREE.Mesh(a,b);Entity.vector.copy(game.config.forward);Entity.vector.multiplyScalar(10);this.crosshair.position.copy(Entity.vector)};
Entity.prototype.setModel=function(a){Entity.hasComponent(this.avatar)||(this.avatar={});this.avatar.model=a};Entity.prototype.fireProjectileFrom=function(a,b){this.ai.owner=a.parent;this.ai.subtype=a.item.name;this.graphics.position.setFromMatrixPosition(a.graphics.matrixWorld);this.physics.oldDelta=b;this.physics.oldPosition.copy(a.parent.physics.oldPosition);a.getForward().multiplyScalar(-this.ai.speed*b);this.physics.oldPosition.add(Entity.vector)};
Entity.prototype.createParticles=function(a,b){var c=new THREE.Geometry;c.vertices.push(new THREE.Vector3(0,.1,0));c.vertices.push(new THREE.Vector3(1,1,1));c.vertices.push(new THREE.Vector3(2,2,-1.5));c.vertices.push(new THREE.Vector3(0,3,2));var d=ResourceLoader.loadTexture("sprite.png"),d=new THREE.PointCloudMaterial({size:b,map:d,transparent:!0}),c=new THREE.PointCloud(c,d);c.position.copy(a);return c};
Entity.prototype.createBubble=function(a,b){var c=new THREE.MeshBasicMaterial({color:16724736,transparent:!0,opacity:.5}),d=new THREE.SphereGeometry(b,16,16),c=new THREE.Mesh(d,c);c.position.copy(a);return c};
Entity.prototype.setExplosion=function(a,b,c){this.ai={alive:!0,radius:game.config.explosion_size,explosionstart:game.time,owner:b,damage:c.damage};Entity.hasComponent(c.splash)&&(this.ai.radius*=c.splash);this.graphics=this.createParticles(a,this.ai.radius);this.parent.graphics.add(this.graphics);this.explodePlayers()};Entity.prototype.explosionHitsObject=function(a){return this.graphics.position.distanceTo(a.position)<a.geometry.boundingSphere.radius+this.ai.radius?!0:!1};
Entity.prototype.explodePlayers=function(){for(var a in game.players){var b=game.players[a];this.explosionHitsObject(b.getCollisionMesh())&&(game.log("explosion ",this," hits player: ",b),b.damagePlayer(this.ai.damage,this.ai.owner))}};Entity.prototype.killExplosion=function(){this.removeGraphics()};Entity.prototype.explodeProjectile=function(a){game.log("exploding",this);game.createExplosion(this.graphics.position,this.ai.owner,this.item);this.removeGraphics()};
Entity.prototype.damagePlayer=function(a,b){console.log("player hit with damage",a,b);this.ai.health-=a;this.ai.alive&&0>=this.ai.health&&this.player.index!=b.player.index&&b.avatar.kills++};
Entity.prototype.loadData=function(a){a=a||!1;if(Entity.hasComponent(this.avatar)){if(Entity.hasComponent(this.avatar.model)){if(!Entity.hasComponent(this.graphics)){this.graphics=this.getPlaceHolder();if(Entity.hasComponent(this.avatar.geometry)&&Entity.hasComponent(this.avatar.material)){game.log("Using cached model");var b=null,b=a?new THREE.SkinnedMesh(this.avatar.geometry,this.avatar.material):new THREE.Mesh(this.avatar.geometry,this.avatar.material);this.finalizeGraphics(b);return}this.collisionMesh=
this.graphics;Entity.hasComponent(this.parent)&&this.parent.graphics.add(this.graphics)}a?(game.log("loadAnimated:",this,this.avatar.name),this.loadAnimatedModel(this.avatar.model)):(game.log("loadModel:",this,this.avatar.name),this.loadModel(this.avatar.model))}Entity.hasComponent(this.avatar.collision)&&(game.log("load collision model:",this.avatar.name),this.loadCollisionModel(this.avatar.collision))}};
var ResourceLoader={emptyGeometry:new THREE.BoxGeometry(3,3,3,2,2,2),emptyMaterial:new THREE.MeshBasicMaterial({color:255}),textureCache:{},dataPath:function(a){return game.config.basepath+game.config.datapath+a},getPlaceHolder:function(){var a=new THREE.SkinnedMesh(this.emptyGeometry,this.emptyMaterial,!1);a.geometry.computeBoundingSphere();a.geometry.computeBoundingBox();a.name="placeholder";return a},loadingError:function(a,b,c){game.error("Error while loading "+a+": "+b+" - "+c)},loadConfiguration:function(a){var b=
a.config.basepath+a.config.configuration_file;$.ajax({url:b,cache:!a.config.DEBUG,dataType:"json",success:function(b){for(var d in b)a.config[d]=b[d]},error:function(a,d,e){ResourceLoader.loadingError(b,d,e)},complete:function(){a.init()}})},loadEntities:function(a,b,c){for(var d=function(a,b,c){ResourceLoader.loadingError(e,b,c)};a.length;){var e=ResourceLoader.dataPath(a.pop());$.ajax({cache:!game.config.DEBUG,url:e,dataType:"json",success:b,error:d,complete:c})}},loadSound:function(a,b){var c=
ResourceLoader.dataPath(a);game.log("Loading audio:",c);var d=new XMLHttpRequest;d.open("GET",c,!0);d.responseType="arraybuffer";var e=new Sound(null);d.onload=function(){b.decodeAudio(e,d.response)};d.send();return e},loadTexture:function(a){return a in textureCache?textureCache[a]:THREE.ImageUtils.loadTexture(a)},loadCollisionModel:function(a,b){game.log("Loading collision model "+a);(new THREE.JSONLoader).load(ResourceLoader.dataPath(a),function(a,d){var e=new THREE.MeshBasicMaterial({color:16711680}),
e=new THREE.Mesh(a,e);b.setMeshProperties(e,b.avatar);b.collisionMesh=e})},loadModel:function(a,b){game.log("Loading model "+a);(new THREE.JSONLoader).load(ResourceLoader.dataPath(a),function(a,d){var e=ResourceLoader.loadMaterial(a,d),f=new THREE.Mesh(a,e);b.avatar.geometry=a;b.avatar.material=e;b.finalizeGraphics(f)})},loadMaterial:function(a,b){return new THREE.MeshPhongMaterial({color:2245666,specular:2250018,shininess:10,shading:THREE.FlatShading})},loadAnimatedModel:function(a,b){game.log("Loading skinned model "+
a);(new THREE.JSONLoader).load(ResourceLoader.dataPath(a),function(a,d){var e=ResourceLoader.loadSkinnedMaterial(a,d),f=new THREE.SkinnedMesh(a,e,!1);f.pose();b.avatar.geometry=a;b.avatar.material=e;b.finalizeGraphics(f);Entity.hasComponent(a.animations)&&0<a.animations.length&&(b.avatar.animation=new THREE.Animation(f,a.animations[0]),b.avatar.animation.play(0))})},loadSkinnedMaterial:function(a,b){return new THREE.MeshPhongMaterial({color:6702114,specular:39168,shininess:30,shading:THREE.FlatShading})}};
Entity.prototype.moveGraphicsRelationsTo=function(a){var b=this.graphics;this.graphics=a;for(a=b.children;0<a.length;)this.graphics.add(a[a.length-1]);Entity.hasComponent(this.parent.graphics)&&(this.parent.graphics.remove(b),this.parent.graphics.add(this.graphics))};
Entity.prototype.setMeshProperties=function(a,b){a.name=b.name;b.geometry=a.geometry;b.material=a.material;a.position.copy(this.graphics.position);a.rotation.copy(this.graphics.rotation);a.scale.copy(this.graphics.scale);Entity.hasComponent(b)&&(Entity.hasComponent(b.scale)&&a.scale.set(b.scale.x,b.scale.y,b.scale.z),Entity.hasComponent(b.rotation)&&a.rotation.set(b.rotation.x,b.rotation.y,b.rotation.z),Entity.hasComponent(b.position)&&a.position.set(b.position.x,b.position.y,b.position.z));a.geometry.computeBoundingSphere();
a.geometry.computeBoundingBox()};Entity.prototype.removeGraphics=function(){Entity.hasComponent(this.parent.graphics)&&this.parent.graphics.remove(this.graphics);Entity.hasComponent(this.feet)&&this.parent.graphics.remove(this.feet)};
Entity.prototype.finalizeGraphics=function(a){this.setMeshProperties(a,this.avatar);this.moveGraphicsRelationsTo(a);Entity.hasComponent(this.avatar)&&Entity.hasComponent(this.avatar.name)&&(this.graphics.name=this.avatar.name);Entity.hasComponent(this.avatar.collision)||(this.collisionMesh=this.graphics);Entity.hasComponent(this.ai)&&Entity.hasComponent(this.ai.type)&&("flyer"==this.ai.type||"projectile"==this.ai.type)&&game.scene.add(this.feet);Entity.hasComponent(this.item)&&"gun"==this.item.type&&
game.scene.add(this.shot);Entity.hasComponent(this.crosshair)&&this.graphics.add(this.crosshair)};Entity.prototype.updateInput=function(a){"local"==this.player.connection&&Entity.hasComponent(this.graphics)&&("walker"==this.ai.type?this.handleWalk():"flyer"==this.ai.type?this.handleFly():(game.log("Unknown avatar type: ",this.ai.type,this),game.error("Unknown avatar type: "+this.ai.type)),this.handleActions())};
Entity.prototype.handleActions=function(a){var b=this.player.controls,c=this.graphics;Input.keys[b.primary]?(0<this.items.length&&this.fire(this.items[0],a),c.material.color.setHex(65280)):Input.keys[b.secondary]?(1<this.items.length&&this.fire(this.items[1],a),c.material.color.setHex(255)):c.material.color.setHex(16711680)};
Entity.prototype.fire=function(a,b){var c=a.item;if(game.time-a.ai.lastFired>game.config.item_cooldown*c.cooldown)switch(a.ai.lastFired=game.time,c.type){case "gun":this.fireGun(a);break;case "projectile":this.fireProjectile(a,b);break;case "special":game.createExplosion(this.graphics.position,a.ai.owner,a);this.fireSpecial(a);break;case "particle":this.fireFlamer(a);break;case "laser":this.fireLaser(a);break;default:game.error("Not implemented "+c.type)}};
Entity.prototype.getOwningPlayer=function(){if(Entity.hasComponent(this.projectile))return this.parent;if(Entity.hasComponent(this.player))return this;if(Entity.hasComponent(this.item))return this.item.parent};Entity.prototype.getTargetPlayer=function(){return null};Entity.prototype.getCollisionMesh=function(){return this.graphics};
Entity.prototype.fireGun=function(a){a.shot.position.setFromMatrixPosition(a.graphics.matrixWorld);var b=a.shot.position,c=a.getForward();Entity.ray.set(b,c);this.shootPlayers(a);this.shootGround(a)};Entity.prototype.shootPlayers=function(a){for(var b in game.players){var c=game.players[b];0<Entity.ray.intersectObject(c.getCollisionMesh()).length&&(game.log("shot ",a," hits player: ",c),c.damagePlayer(a.item.damage,this.ai.owner))}};
Entity.prototype.shootGround=function(a){var b=game.field.getCollisionMesh(),b=Entity.ray.intersectObject(b);0<b.length?(a.shot.position.copy(b[0].point),a.shot.lookAt(b[0].face.normal),game.createExplosion(b[0].point,a.ai.owner,a.item)):(a.shot.lookAt(Entity.ray.ray.direction.add(a.shot.position)),game.createExplosion(a.shot.position,a.ai.owner,a.item))};Entity.prototype.fireProjectile=function(a,b){game.log("Firing: ",a.item.name);game.createProjectile(a,b)};
Entity.prototype.fireSpecial=function(a){game.log("Firing: ",a.item.name);"selfdestruct"==a.item.name?(this.createExplosion(this,a.item),this.alive=!1):fireSpecial(a)};Entity.prototype.fireFlamer=function(a){game.log("Firing: ",a.item.name);fireFlamer(a)};Entity.prototype.fireLaser=function(a){game.log("Firing: ",a.item.name);fireLaser(a)};
Entity.prototype.handleProjectile=function(a){var b=this.graphics;Entity.vector3.copy(b.position);Entity.vector="missiles"==this.ai.subtype?this.ai.owner.getForward().multiplyScalar(this.ai.speed):this.getForward().multiplyScalar(this.ai.speed);this.physics.gravity&&Entity.vector.add(Entity.gravity);Entity.vector2=b.position.add(Entity.vector);b.lookAt(Entity.vector2);b.position.copy(Entity.vector2);this.physics.oldPosition.copy(Entity.vector3);this.physics.oldDelta=a};
Entity.prototype.handleFly=function(a){a=this.player.controls;var b=this.graphics;Entity.vector=this.getForward().multiplyScalar(this.ai.speed);Input.keys[a.up]&&(Entity.vector.y+=this.ai.speed);Input.keys[a.down]&&(Entity.vector.y-=this.ai.speed);b.position.add(Entity.vector);Input.keys[a.left]&&(Entity.quaternion.setFromAxisAngle(Entity.up,this.ai.turn),Entity.quaternion.multiplyQuaternions(b.quaternion,Entity.quaternion),b.setRotationFromQuaternion(Entity.quaternion));Input.keys[a.right]&&(Entity.quaternion.setFromAxisAngle(Entity.up,
-this.ai.turn),Entity.quaternion.multiplyQuaternions(b.quaternion,Entity.quaternion),b.setRotationFromQuaternion(Entity.quaternion))};
Entity.prototype.handleWalk=function(a){a=this.player.controls;var b=this.graphics;Input.keys[a.up]&&b.position.add(this.getForward().multiplyScalar(this.ai.speed));Input.keys[a.down]&&b.position.add(this.getForward().multiplyScalar(-this.ai.speed));Input.keys[a.left]&&(Entity.quaternion.setFromAxisAngle(Entity.up,this.ai.turn),Entity.quaternion.multiplyQuaternions(b.quaternion,Entity.quaternion),b.setRotationFromQuaternion(Entity.quaternion));Input.keys[a.right]&&(Entity.quaternion.setFromAxisAngle(Entity.up,
-this.ai.turn),Entity.quaternion.multiplyQuaternions(b.quaternion,Entity.quaternion),b.setRotationFromQuaternion(Entity.quaternion))};Entity.prototype.updatePhysics=function(a){var b=[];Entity.hasComponent(this.player)?(b=this.considerSurface(a,game.field),this.handleGroundIntersects(b)):Entity.hasComponent(this.avatar)&&"projectile"==this.ai.type&&(this.handleProjectile(),b=this.considerSurface(a,game.field),this.handleGroundIntersects(b))};
Entity.prototype.handleGroundIntersects=function(a){0<a.length?(a=a[0],this.feet.position.copy(a.point),"walker"==this.ai.type?(this.graphics.position.y=this.feet.position.y+game.config.feet_end_height,Entity.quaternion.setFromUnitVectors(a.face.normal,Entity.up),Entity.quaternion.multiplyQuaternions(Entity.quaternion,this.graphics.quaternion)):a.distance-game.config.feet_start_height<this.graphics.geometry.boundingSphere.radius&&("projectile"==this.ai.type?this.projectileHitsGround():"player"==this.ai.type&&
this.playerHitsGround())):(game.log("misses the ground"),Entity.hasComponent(this.player)?this.playerDies():this.projectileHitsGround())};Entity.prototype.playerHitsGround=function(){game.assert(Entity.hasComponent(this.player)&&"flyer"==this.ai.type,"playerHitsGround called for a non-flyer ");game.log(this);game.log("TODO: player hits the ground and exploded!");this.playerDies()};Entity.prototype.projectileHitsGround=function(){game.log("projectileHitsGround!",this.ai);this.ai.alive=!1};
Entity.prototype.playerDies=function(){this.ai.alive=!1;game.createExplosion(this.graphics.position,game.items.selfdestruct,this);this.graphics.position.set(0,100,0);this.graphics.material.color.setHex(16711935)};
Entity.prototype.considerObject=function(a,b){for(var c=this.getCollisionMesh(),d=this.graphics.position,e=this.graphics.matrix,c=c.geometry.vertices,f=c.length,g=0;g<f;g++){Entity.vector.copy(c[g]);Entity.vector.applyMatrix4(e);Entity.vector2.copy(Entity.vector.sub(d));var k=Entity.vector2.length;Entity.ray.set(Entity.vector,Entity.vector2);var h=Entity.ray.intersectObject(b);if(0<h.length&&h[0].distance<k)return h}return null};
Entity.prototype.considerSurface=function(a,b){var c=b.getCollisionMesh();Entity.vector.setFromMatrixPosition(this.graphics.matrixWorld);Entity.vector.y+=game.config.feet_start_height;Entity.ray.set(Entity.vector,Entity.gravity);return Entity.ray.intersectObject(c)};
Entity.prototype.updateAnimation=function(a){var b=this.graphics;Entity.hasComponent(b)&&Entity.hasComponent(b.morphTargetInfluences)&&this.animateModel(b,a);Entity.hasComponent(this.ai)&&Entity.hasComponent(this.ai.explosionstart)&&(this.graphics.scale.y*=1.01,5<game.time-this.ai.explosionstart&&(this.ai.alive=!1))};
Entity.prototype.animateModel=function(a){a=this.graphics;var b=0,c=Date.now()%1E3,d=Math.floor(c/50);1!=d&&(a.morphTargetInfluences[b]=0,a.morphTargetInfluences[1]=1,a.morphTargetInfluences[d]=0,b=1);a.morphTargetInfluences[d]=c%50/50;a.morphTargetInfluences[b]=1-a.morphTargetInfluences[d]};Entity.prototype.getForward=function(){Entity.matrix.extractRotation(this.graphics.matrixWorld);Entity.vector.copy(Entity.forward);return Entity.vector.applyMatrix4(Entity.matrix)};
var Eto=function(){this.CONFIG=ETO_CONFIG_DEFAULT;this.characters={};this.items={};this.maps=[];this.players=[];this.projectiles=[];this.explosions=[];this.renderer=this.scene=this.camera=this.field=null;this.resetRequested=this.isRunning=!1;this.clock=new THREE.Clock;this.averageFps=this.frameCounter=this.frameTime=0};Object.defineProperty(Eto.prototype,"time",{get:function(){return this.frameTime}});Object.defineProperty(Eto.prototype,"config",{get:function(){return this.CONFIG}});
Eto.prototype.initCamera=function(a){a.position.set(this.config.camera_position.x,this.config.camera_position.y,this.config.camera_position.z);a.up=new THREE.Vector3(this.config.camera_up.x,this.config.camera_up.y,this.config.camera_up.z);a.lookAt(new THREE.Vector3(this.config.camera_lookat.x,this.config.camera_lookat.y,this.config.camera_lookat.z))};
Eto.prototype.createCamera=function(){var a=new THREE.PerspectiveCamera(this.config.camera_fov,window.innerWidth/window.innerHeight,this.config.camera_near,this.config.camera_far);this.initCamera(a);return a};
Eto.prototype.createScene=function(){var a=new THREE.Scene;a.name=this.config.title;this.master=new Entity(null);this.master.parent=this.master;this.master.graphics=a;a.add(new THREE.AxisHelper(50));this.sky=this.createSky();a.add(this.sky);a.add(new THREE.AmbientLight(12303291));var b=new THREE.PointLight(7291936,10,500);b.position.set(100,100,100);a.add(b);return a};
Eto.prototype.createSky=function(){var a=new THREE.SphereGeometry(this.config.sky_size,8,8),b=new THREE.MeshBasicMaterial({color:this.config.sky_color});b.side=THREE.DoubleSide;a=new THREE.Mesh(a,b);a.name="skysphere";return a};Eto.prototype.generateField=function(a){a=new Entity(this.master);var b=new THREE.PlaneGeometry(170,170,3,3),c=new THREE.MeshBasicMaterial({color:1127287,side:THREE.DoubleSided});a.graphics=new THREE.Mesh(b,c);a.graphics.rotateX(-Math.PI/2);a.graphics.translateY(-1);return a};
Eto.prototype.createField=function(a){var b=new Entity(this.master);game.log("Loading map: ",a);b.setAvatar(a);b.loadData();b.graphics.geometry.computeBoundingBox();return b};Eto.prototype.createAudio=function(){return new Audio};Eto.prototype.createMusic=function(a){for(var b in a.music)this.appendOptionToSelect("#soundtracks",a.music[b].src,a.music[b].title);0<a.music.length&&this.selectSong(a.music[0].src)};
Eto.prototype.selectSong=function(a){var b=null,c;for(c in this.config.music_types)if(suffix=this.config.music_types[c].suffix,-1!==a.indexOf(suffix,a.length-suffix.length)){b=this.config.music_types[c].type;break}b?($("#musicplayer").src(a),$("#musicplayer").type(b)):this.error("Unrecognized media type: ",a)};Eto.prototype.createRenderer=function(){var a=new THREE.WebGLRenderer(this.config.renderer_params);a.setPixelRatio(window.devicePixelRatio);a.setSize(window.innerWidth,window.innerHeight);return a};
Eto.prototype.onWindowResize=function(){this.camera.aspect=window.innerWidth/window.innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(window.innerWidth,window.innerHeight)};Eto.prototype.start=function(){this.isRunning=!0;this.isPaused=!1;this.clock.start();this.gameLoop()};Eto.prototype.stop=function(){this.isRunning=!1;this.isPaused=!0;this.clock.stop()};Eto.prototype.togglePause=function(){this.isPaused?(this.isPaused=!1,this.clock.start()):(this.isPaused=!0,this.clock.stop())};
Eto.prototype.gameLoop=function(){requestAnimationFrame(this.gameLoop.bind(this));this.resetRequested&&(this.resetRequested=!1,this.reset());this.isRunning&&(this.update(),this.renderer.render(this.scene,this.camera))};Eto.prototype.updateFps=function(a){this.frameCounter++;this.averageFps+=(a-this.averageFps)/this.frameCounter;240==this.frameCounter&&(this.showFps(a),this.averageFps=this.frameCounter=0)};
Eto.prototype.update=function(){var a=this.clock.getDelta();this.isPaused||(this.updateFps(1/a),this.startUpdate(a),this.updateInput(a),this.updateAnimation(a),this.updatePhysics(a),this.updateCamera(a))};
Eto.prototype.startUpdate=function(a){this.frameTime+=a;for(var b=this.players.length;0<b--;){var c=this.players[b];c.startUpdate(a);c.ai.alive||this.playerDied(b)}for(b=this.projectiles.length;0<b--;)c=this.projectiles[b],c.startUpdate(a),c.ai.alive||this.projectileDied(b,a);for(b=this.explosions.length;0<b--;)c=this.explosions[b],c.startUpdate(a),c.ai.alive||this.explosionDied(b,a)};Eto.prototype.updateInput=function(a){for(var b=0;b<this.players.length;++b)this.players[b].updateInput(a)};
Eto.prototype.updateAnimation=function(a){for(var b=0;b<this.players.length;++b)this.players[b].updateAnimation(a);for(b=0;b<this.projectiles.length;++b)this.projectiles[b].updateAnimation(a,this.field);for(b=0;b<this.explosions.length;++b)this.explosions[b].updateAnimation(a,this.field);THREE.AnimationHandler.update(a)};
Eto.prototype.updatePhysics=function(a){for(var b=0;b<this.players.length;++b)this.players[b].updatePhysics(a,this.field);for(b=0;b<this.projectiles.length;++b)this.projectiles[b].updatePhysics(a,this.field)};Eto.prototype.updateCamera=function(a){Entity.vector.set(0,0,0);Entity.vector.divideScalar(this.players.length)};Eto.prototype.loadMaps=function(a){for(var b in a){var c=a[b].name;this.maps[c]=a[b];this.appendOptionToSelect("#maps",b,c)}};
Eto.prototype.loadCharacters=function(a){for(var b in a){var c=a[b].name;this.characters[c]=a[b];this.appendOptionToSelect("#p0chars",c,c);this.appendOptionToSelect("#p1chars",c,c)}};Eto.prototype.loadItems=function(a){for(var b in a)this.items[b]=a[b],this.items[b].name=b};Eto.prototype.loadEntities=function(a){var b=a.slice(0);ResourceLoader.loadEntities(b,succesfun,function(){0===b.length&&game.entitiesLoaded()})};
Eto.prototype.createConnections=function(){this.connection=new RTCPeerConnection;var a=this.connection.createDataChannel("game");a.onopen=function(b){a.send("MESSAGE!")};a.onmessage=function(a){game.log(a,a.data)}};Eto.prototype.closeConnections=function(){this.connection.close()};Eto.prototype.randomizeMap=function(){var a=Object.keys(this.maps);this.random();return this.maps[a[1]]};
Eto.prototype.randomizeCharacter=function(a){a=this.getSuggestedPlayerCharacter(a);var b=this.characters[a];if("undefined"===typeof b||null===b)game.log("Unknown character '"+a+"', randomizing"),a=Object.keys(this.characters),b=Math.floor(Math.random()*a.length),b=this.characters[a[b]];return b};Eto.prototype.randomizePosition=function(a){game.log("Randomized position. TODO: Use actual random field position!");a.graphics.position.set(0,0,0)};
Eto.prototype.incarnatePlayer=function(a,b){a.setAvatar(this.randomizeCharacter(b));a.setPlayer(this.config.players[b]);a.avatar.name="player";a.loadData(!0);this.loadPlayerItems(a);this.randomizePosition(a)};Eto.prototype.createPlayer=function(a){var b=new Entity(this.master);this.incarnatePlayer(b,a);return b};Eto.prototype.playerDied=function(a){game.log("Player "+a+" died!");var b=this.players[a];b.player.deaths++;this.showPlayerStats();this.incarnatePlayer(b,a)};
Eto.prototype.loadPlayerItems=function(a){for(var b=0;b<a.graphics.children.length;++b)a.graphics.remove(a.graphics.children[b]);a.items=[];for(b=0;b<a.avatar.items.length;++b){var c=new Entity(a);c.setAvatar(a.avatar.items[b]);c.setItem(this.items[c.avatar.name]);c.loadData();a.items.push(c)}};
Eto.prototype.createProjectile=function(a,b){var c=new Entity(this.master);c.setAvatar(a.item.projectile);c.setProjectile(a.item.projectile);c.loadData();c.fireProjectileFrom(a,b);game.log("Item:",a," creates projectile:",c);this.projectiles.push(c)};Eto.prototype.projectileDied=function(a,b){game.log("Projectile "+a+" died!");this.projectiles[a].explodeProjectile(b);this.projectiles.splice(a,1)};
Eto.prototype.explosionDied=function(a,b){game.log("Explosion "+a+" died!");this.explosions[a].killExplosion();this.explosions.splice(a,1)};Eto.prototype.createExplosion=function(a,b,c){var d=new Entity(this.master);d.setExplosion(a,b,c);this.explosions.push(d)};Eto.prototype.random=function(){return Math.random()};Eto.prototype.log=ETO_CONFIG_DEFAULT.DEBUG?window.console.log.bind(window.console):function(){};
Eto.prototype.error=function(a){game.log(a);game.log("*** Stack trace: ",Error().stack);this.config.DEBUG&&alert(a)};Eto.prototype.assert=function(a,b){a||this.error(b)};Eto.prototype.requestReset=function(){game.log("Reset requested!");this.resetRequested=!0};Eto.prototype.reset=function(){game.log("Resetting game! TODO: actually reset!");this.players[0].alive=!1;this.players[1].alive=!1};Eto.prototype.clearField=function(){this.players=[];this.projectiles=[]};
Eto.prototype.createGame=function(){this.field=this.createField(this.randomizeMap());for(var a=0;a<this.config.playercount;++a)this.players.push(this.createPlayer(a));this.start()};Eto.prototype.entitiesLoaded=function(){this.clearField();this.createGame()};Eto.prototype.getSuggestedPlayerCharacter=function(a){return $("#p"+a+"chars").val()};Eto.prototype.appendOptionToSelect=function(a,b,c){$(a).append($("<option />").val(b).html(c))};
Eto.prototype.setPlayerStrength=function(a){a=a.data;var b=$(this).val();game.log("TODO: set player ",a," hp+pwr to reflect value ",b)};Eto.prototype.showPlayerHealth=function(a,b){};Eto.prototype.showFps=function(a){$("#fpscounter").text(a.toFixed(2))};Eto.prototype.showPlayerStats=function(){for(var a in this.players)$("#score > #player"+a+" > #kills").val(a.kills),$("#score > #player"+a+" > #deaths").val(a.deaths)};Eto.prototype.toggleMenu=function(){$("#settings").toggleClass("hidden");this.togglePause()};
Eto.prototype.setGui=function(){$(document).on("keydown",Input.keyDown);$(document).on("keyup",Input.keyUp);$("#p1strength").on("change",this.setPlayerStrength.bind(this),0);$("#p2strength").on("change",this.setPlayerStrength.bind(this),1);$("#reset").on("click",this.requestReset.bind(this));this.config.play_music&&($("#soundtracks").on("change",function(a){game.selectSong($("#soundtracks").val())}),this.createMusic(field));$("#disconnect").on("click",function(){game.audio.playSound(bello.buffer);
game.error("DISCO!")})};Eto.prototype.initGame=function(){game.log("config",this.config);this.loadEntities(this.config.entities)};var bello=null;
Eto.prototype.init=function(){this.renderer=this.createRenderer();document.getElementById("container").appendChild(this.renderer.domElement);this.connections=this.createConnections();this.audio=this.createAudio();bello=ResourceLoader.loadSound("recycle.wav",this.audio);this.camera=this.createCamera();this.scene=this.createScene();$(window).on("resize",this.onWindowResize.bind(this));this.setGui();this.initGame()};var game=new Eto;ResourceLoader.loadConfiguration(game);
